//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafeteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Informes = new HashSet<Informe>();
            this.Productos_Pedido = new HashSet<Productos_Pedido>();
        }
    
        public int Id_Pedido { get; set; }
        public int Id_Cliente { get; set; }
        public string Estado_Producto { get; set; }
        public string MetodoPago { get; set; }
        public System.DateTime FechaPedido { get; set; }
    
        public virtual ClientesCafeteria ClientesCafeteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe> Informes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos_Pedido> Productos_Pedido { get; set; }
    }
}
